export const PAGE_SIZE = 3;
export const AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDE2NTM2MjYsImNsaWVudElkIjoiY2o1amNkOTJiaXYwZzAxMjc4cHVzZm9kdCIsInByb2plY3RJZCI6ImNqNXVrdWQzbXVhM3UwMTIyajQ1ZmIxbG0iLCJwZXJtYW5lbnRBdXRoVG9rZW5JZCI6ImNqNXVsc3B5enY5ZmUwMTIyYXBlbDFqcW4ifQ.2BrzNxMTCJ_Oum-KAWAJ9rzwsLTM0eSayXQf2njkTiA';
export const API_ENDPOINTS = 'https://api.graph.cool/simple/v1/cj5ukud3mua3u0122j45fb1lm';
